### ISSUE TITLE
Docstrings em vez de comentários

### ISSUE THREAD

**Issue by lkrippahl** [lkrippahl/eHooke#1]
No image loader há comentários onde devia haver docstrings. Exemplo:

http://sphinxcontrib-napoleon.readthedocs.org/en/latest/example_google.html

Também é preciso mudar os nomes dos módulos

**Comment by brunomsaraiva** [comment]
já mudei os nomes dos módulos e mudei para docstring todos os comentários que fazem sentido para o utilizador e não para quem vai mexer no código (estes últimos deixei como comments).
