### ISSUE TITLE
O modulo ehook.py deve ser ehooke.py e deve encapsular todo o programa numa classe EHooke. Desta forma a classe pode ser importada para o servidor.

### ISSUE THREAD

**Issue by lkrippahl** [lkrippahl/eHooke#2]
Desta forma a classe pode ser importada para o servidor, que terá de gerir várias instâncias do programa (desta classe)

O main do ehooke.py deve ser apenas para correr uma classe, e deve ter a possibilidade de processar argumentos, pelo menos para indicar o ficheiro de parâmetros a ler (para se correr a partir de um batch) Não precisas de fazer isto já, mas deixa lá o comentário com a tag TODO.

**Comment by lkrippahl** [comment]
Desta forma a classe pode ser importada para o servidor, que terá de gerir várias instâncias do programa (desta classe)

O main do ehooke.py deve ser apenas para correr uma classe, e deve ter a possibilidade de processar argumentos, pelo menos para indicar o ficheiro de parâmetros a ler (para se correr a partir de um batch) Não precisas de fazer isto já, mas deixa lá o comentário com a tag TODO.

**Comment by brunomsaraiva** [comment]
Nome do módulo corrigido e esqueleto da classe criada, falta depois definir os métodos e atributos da classe
