### ISSUE TITLE
O modulo ehloader serve para quê?

### ISSUE THREAD

**Issue by lkrippahl** [lkrippahl/eHooke#3]
Se for para carregar os ficheiros ehk com os parâmetros, acho melhor incluir isso no parameters.py (a menos que haja alguma razão para separar...)

Seja como for, quando criares módulos em vez de """placeholder""" escreve uma breve descrição do que o módulo vai fazer.

**Comment by brunomsaraiva** [comment]
módulo removido do repositório (a utilização do mesmo passa para o módulo ehooke.py)
